//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bll
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public string UserName { get; set; }
        public string Text { get; set; }
        public int CommentId { get; set; }
        public int ID { get; set; }
        public int Type { get; set; }
        public string UserProfilePicture { get; set; }
        public System.DateTime date { get; set; }
    }
}
