//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bll
{
    using System;
    using System.Collections.Generic;
    
    public partial class Editors
    {
        public string UserID { get; set; }
        public int AnimeID { get; set; }
        public int Edit { get; set; }
        public int Id { get; set; }
    }
}
