//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bll
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Number { get; set; }
        public int SessionID { get; set; }
        public string Uploder { get; set; }
        public string VideoUrl { get; set; }
        public int AnimeID { get; set; }
        public System.DateTime Uplload { get; set; }
    
        public virtual Animes Animes { get; set; }
        public virtual Session Session { get; set; }
    }
}
